//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_de_Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SistemaInfraccionesDBEntities : DbContext
    {
        public SistemaInfraccionesDBEntities()
            : base("name=SistemaInfraccionesDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Infraccion> Infraccion { get; set; }
        public virtual DbSet<PagoInfraccion> PagoInfraccion { get; set; }
        public virtual DbSet<Vehiculo> Vehiculo { get; set; }
    }
}
